namespace BPSR_DeepsLib.ServiceMethods;

public enum WorldNtf
{
    EnterScene = 0x3,
    NotifyLoadSceneEnd = 0x4,
    Teleport = 0x5,
    SyncNearEntities = 0x6,
    SyncSceneAttrs = 0x7,
    SyncSceneEvents = 0x8,
    SyncEntityBehaviorTree = 0x9,
    SyncPlayCameraAnimation = 0xA,
    SyncFieldOfView = 0xB,
    SyncLog = 0xC,
    SyncPathNode = 0xD,
    SyncServerData = 0xF,
    ForcedPullBack = 0x10,
    LineDrawing = 0x11,
    EnterGame = 0x14,
    SyncContainerData = 0x15,
    SyncContainerDirtyData = 0x16,
    SyncDungeonData = 0x17,
    SyncDungeonDirtyData = 0x18,
    SyncPersonalObject = 0x22,
    PersonalObjectUpdate = 0x23,
    NotifyReviveUser = 0x27,
    SyncServerTime = 0x2B,
    SyncNearDeltaInfo = 0x2D,
    SyncToMeDeltaInfo = 0x2E,
    NotifyClientKickOff = 0x31,
    PersonalGroupObjectUpdate = 0x3C,
    NotifyUserCloseFunction = 0x3E,
    NotifyServerCloseFunction = 0x3F,
    BounceJump = 0x42,
    ServerStateObjectUpdate = 0x43,
    SyncAllServerStateObject = 0x44,
    NotifyTimerList = 0x48,
    NotifyTimerUpdate = 0x49
}