// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: stru_fashion_mgr.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zproto {

  /// <summary>Holder for reflection information generated from stru_fashion_mgr.proto</summary>
  public static partial class StruFashionMgrReflection {

    #region Descriptor
    /// <summary>File descriptor for stru_fashion_mgr.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StruFashionMgrReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZzdHJ1X2Zhc2hpb25fbWdyLnByb3RvEgZ6cHJvdG8aH3N0cnVfZmFzaGlv",
            "bl9hZHZhbmNlX2luZm8ucHJvdG8aHXN0cnVfZmFzaGlvbl9jb2xvcl9pbmZv",
            "LnByb3RvGhxzdHJ1X3VubG9ja19jb2xvcl9pbmZvLnByb3RvGhVzdHJ1X2Rp",
            "cnR5X21hc2sucHJvdG8iwwsKCkZhc2hpb25NZ3ISMgoId2VhckluZm8YASAD",
            "KAsyIC56cHJvdG8uRmFzaGlvbk1nci5XZWFySW5mb0VudHJ5EjoKDGZhc2hp",
            "b25EYXRhcxgCIAMoCzIkLnpwcm90by5GYXNoaW9uTWdyLkZhc2hpb25EYXRh",
            "c0VudHJ5EjgKC1VubG9ja0NvbG9yGAMgAygLMiMuenByb3RvLkZhc2hpb25N",
            "Z3IuVW5sb2NrQ29sb3JFbnRyeRI8Cg1mYXNoaW9uUmV3YXJkGAQgAygLMiUu",
            "enByb3RvLkZhc2hpb25NZ3IuRmFzaGlvblJld2FyZEVudHJ5EjYKCmFsbEZh",
            "c2hpb24YBSADKAsyIi56cHJvdG8uRmFzaGlvbk1nci5BbGxGYXNoaW9uRW50",
            "cnkSMAoHYWxsUmlkZRgGIAMoCzIfLnpwcm90by5GYXNoaW9uTWdyLkFsbFJp",
            "ZGVFbnRyeRI8Cg1hbGxXZWFwb25Ta2luGAcgAygLMiUuenByb3RvLkZhc2hp",
            "b25NZ3IuQWxsV2VhcG9uU2tpbkVudHJ5Ej4KDmZhc2hpb25BZHZhbmNlGAgg",
            "AygLMiYuenByb3RvLkZhc2hpb25NZ3IuRmFzaGlvbkFkdmFuY2VFbnRyeRIb",
            "ChNmYXNoaW9uQ29sbGVjdFBvaW50GAkgASgFEhgKEHJpZGVDb2xsZWN0UG9p",
            "bnQYCiABKAUSHgoWd2VhcG9uU2tpbkNvbGxlY3RQb2ludBgLIAEoBRI8Cg1h",
            "bGxGYXNoaW9uTnVtGAwgAygLMiUuenByb3RvLkZhc2hpb25NZ3IuQWxsRmFz",
            "aGlvbk51bUVudHJ5EjYKCmFsbFJpZGVOdW0YDSADKAsyIi56cHJvdG8uRmFz",
            "aGlvbk1nci5BbGxSaWRlTnVtRW50cnkSQgoQYWxsV2VhcG9uU2tpbk51bRgO",
            "IAMoCzIoLnpwcm90by5GYXNoaW9uTWdyLkFsbFdlYXBvblNraW5OdW1FbnRy",
            "eRIVCg1pc0Zhc2hpb25Jbml0GA8gASgIEhIKCmlzUmlkZUluaXQYECABKAgS",
            "GAoQaXNXZWFwb25Ta2luSW5pdBgRIAEoCBovCg1XZWFySW5mb0VudHJ5EgsK",
            "A2tleRgBIAEoBRINCgV2YWx1ZRgCIAEoBToCOAEaTQoRRmFzaGlvbkRhdGFz",
            "RW50cnkSCwoDa2V5GAEgASgFEicKBXZhbHVlGAIgASgLMhguenByb3RvLkZh",
            "c2hpb25Db2xvckluZm86AjgBGksKEFVubG9ja0NvbG9yRW50cnkSCwoDa2V5",
            "GAEgASgFEiYKBXZhbHVlGAIgASgLMhcuenByb3RvLlVubG9ja0NvbG9ySW5m",
            "bzoCOAEaNAoSRmFzaGlvblJld2FyZEVudHJ5EgsKA2tleRgBIAEoBRINCgV2",
            "YWx1ZRgCIAEoCDoCOAEaMQoPQWxsRmFzaGlvbkVudHJ5EgsKA2tleRgBIAEo",
            "BRINCgV2YWx1ZRgCIAEoCDoCOAEaLgoMQWxsUmlkZUVudHJ5EgsKA2tleRgB",
            "IAEoBRINCgV2YWx1ZRgCIAEoCDoCOAEaNAoSQWxsV2VhcG9uU2tpbkVudHJ5",
            "EgsKA2tleRgBIAEoBRINCgV2YWx1ZRgCIAEoCDoCOAEaUQoTRmFzaGlvbkFk",
            "dmFuY2VFbnRyeRILCgNrZXkYASABKAUSKQoFdmFsdWUYAiABKAsyGi56cHJv",
            "dG8uRmFzaGlvbkFkdmFuY2VJbmZvOgI4ARo0ChJBbGxGYXNoaW9uTnVtRW50",
            "cnkSCwoDa2V5GAEgASgFEg0KBXZhbHVlGAIgASgFOgI4ARoxCg9BbGxSaWRl",
            "TnVtRW50cnkSCwoDa2V5GAEgASgFEg0KBXZhbHVlGAIgASgFOgI4ARo3ChVB",
            "bGxXZWFwb25Ta2luTnVtRW50cnkSCwoDa2V5GAEgASgFEg0KBXZhbHVlGAIg",
            "ASgFOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zproto.StruFashionAdvanceInfoReflection.Descriptor, global::Zproto.StruFashionColorInfoReflection.Descriptor, global::Zproto.StruUnlockColorInfoReflection.Descriptor, global::Zproto.StruDirtyMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zproto.FashionMgr), global::Zproto.FashionMgr.Parser, new[]{ "WearInfo", "FashionDatas", "UnlockColor", "FashionReward", "AllFashion", "AllRide", "AllWeaponSkin", "FashionAdvance", "FashionCollectPoint", "RideCollectPoint", "WeaponSkinCollectPoint", "AllFashionNum", "AllRideNum", "AllWeaponSkinNum", "IsFashionInit", "IsRideInit", "IsWeaponSkinInit" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, null, null, null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FashionMgr : pb::IMessage<FashionMgr>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FashionMgr> _parser = new pb::MessageParser<FashionMgr>(() => new FashionMgr());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FashionMgr> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zproto.StruFashionMgrReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FashionMgr() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FashionMgr(FashionMgr other) : this() {
      wearInfo_ = other.wearInfo_.Clone();
      fashionDatas_ = other.fashionDatas_.Clone();
      unlockColor_ = other.unlockColor_.Clone();
      fashionReward_ = other.fashionReward_.Clone();
      allFashion_ = other.allFashion_.Clone();
      allRide_ = other.allRide_.Clone();
      allWeaponSkin_ = other.allWeaponSkin_.Clone();
      fashionAdvance_ = other.fashionAdvance_.Clone();
      fashionCollectPoint_ = other.fashionCollectPoint_;
      rideCollectPoint_ = other.rideCollectPoint_;
      weaponSkinCollectPoint_ = other.weaponSkinCollectPoint_;
      allFashionNum_ = other.allFashionNum_.Clone();
      allRideNum_ = other.allRideNum_.Clone();
      allWeaponSkinNum_ = other.allWeaponSkinNum_.Clone();
      isFashionInit_ = other.isFashionInit_;
      isRideInit_ = other.isRideInit_;
      isWeaponSkinInit_ = other.isWeaponSkinInit_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FashionMgr Clone() {
      return new FashionMgr(this);
    }

    /// <summary>Field number for the "wearInfo" field.</summary>
    public const int WearInfoFieldNumber = 1;
    private static readonly pbc::MapField<int, int>.Codec _map_wearInfo_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 10);
    private readonly pbc::MapField<int, int> wearInfo_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> WearInfo {
      get { return wearInfo_; }
    }

    /// <summary>Field number for the "fashionDatas" field.</summary>
    public const int FashionDatasFieldNumber = 2;
    private static readonly pbc::MapField<int, global::Zproto.FashionColorInfo>.Codec _map_fashionDatas_codec
        = new pbc::MapField<int, global::Zproto.FashionColorInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.FashionColorInfo.Parser), 18);
    private readonly pbc::MapField<int, global::Zproto.FashionColorInfo> fashionDatas_ = new pbc::MapField<int, global::Zproto.FashionColorInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.FashionColorInfo> FashionDatas {
      get { return fashionDatas_; }
    }

    /// <summary>Field number for the "UnlockColor" field.</summary>
    public const int UnlockColorFieldNumber = 3;
    private static readonly pbc::MapField<int, global::Zproto.UnlockColorInfo>.Codec _map_unlockColor_codec
        = new pbc::MapField<int, global::Zproto.UnlockColorInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.UnlockColorInfo.Parser), 26);
    private readonly pbc::MapField<int, global::Zproto.UnlockColorInfo> unlockColor_ = new pbc::MapField<int, global::Zproto.UnlockColorInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.UnlockColorInfo> UnlockColor {
      get { return unlockColor_; }
    }

    /// <summary>Field number for the "fashionReward" field.</summary>
    public const int FashionRewardFieldNumber = 4;
    private static readonly pbc::MapField<int, bool>.Codec _map_fashionReward_codec
        = new pbc::MapField<int, bool>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBool(16, false), 34);
    private readonly pbc::MapField<int, bool> fashionReward_ = new pbc::MapField<int, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, bool> FashionReward {
      get { return fashionReward_; }
    }

    /// <summary>Field number for the "allFashion" field.</summary>
    public const int AllFashionFieldNumber = 5;
    private static readonly pbc::MapField<int, bool>.Codec _map_allFashion_codec
        = new pbc::MapField<int, bool>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBool(16, false), 42);
    private readonly pbc::MapField<int, bool> allFashion_ = new pbc::MapField<int, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, bool> AllFashion {
      get { return allFashion_; }
    }

    /// <summary>Field number for the "allRide" field.</summary>
    public const int AllRideFieldNumber = 6;
    private static readonly pbc::MapField<int, bool>.Codec _map_allRide_codec
        = new pbc::MapField<int, bool>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBool(16, false), 50);
    private readonly pbc::MapField<int, bool> allRide_ = new pbc::MapField<int, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, bool> AllRide {
      get { return allRide_; }
    }

    /// <summary>Field number for the "allWeaponSkin" field.</summary>
    public const int AllWeaponSkinFieldNumber = 7;
    private static readonly pbc::MapField<int, bool>.Codec _map_allWeaponSkin_codec
        = new pbc::MapField<int, bool>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBool(16, false), 58);
    private readonly pbc::MapField<int, bool> allWeaponSkin_ = new pbc::MapField<int, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, bool> AllWeaponSkin {
      get { return allWeaponSkin_; }
    }

    /// <summary>Field number for the "fashionAdvance" field.</summary>
    public const int FashionAdvanceFieldNumber = 8;
    private static readonly pbc::MapField<int, global::Zproto.FashionAdvanceInfo>.Codec _map_fashionAdvance_codec
        = new pbc::MapField<int, global::Zproto.FashionAdvanceInfo>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Zproto.FashionAdvanceInfo.Parser), 66);
    private readonly pbc::MapField<int, global::Zproto.FashionAdvanceInfo> fashionAdvance_ = new pbc::MapField<int, global::Zproto.FashionAdvanceInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Zproto.FashionAdvanceInfo> FashionAdvance {
      get { return fashionAdvance_; }
    }

    /// <summary>Field number for the "fashionCollectPoint" field.</summary>
    public const int FashionCollectPointFieldNumber = 9;
    private int fashionCollectPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FashionCollectPoint {
      get { return fashionCollectPoint_; }
      set {
        fashionCollectPoint_ = value;
      }
    }

    /// <summary>Field number for the "rideCollectPoint" field.</summary>
    public const int RideCollectPointFieldNumber = 10;
    private int rideCollectPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RideCollectPoint {
      get { return rideCollectPoint_; }
      set {
        rideCollectPoint_ = value;
      }
    }

    /// <summary>Field number for the "weaponSkinCollectPoint" field.</summary>
    public const int WeaponSkinCollectPointFieldNumber = 11;
    private int weaponSkinCollectPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WeaponSkinCollectPoint {
      get { return weaponSkinCollectPoint_; }
      set {
        weaponSkinCollectPoint_ = value;
      }
    }

    /// <summary>Field number for the "allFashionNum" field.</summary>
    public const int AllFashionNumFieldNumber = 12;
    private static readonly pbc::MapField<int, int>.Codec _map_allFashionNum_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 98);
    private readonly pbc::MapField<int, int> allFashionNum_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> AllFashionNum {
      get { return allFashionNum_; }
    }

    /// <summary>Field number for the "allRideNum" field.</summary>
    public const int AllRideNumFieldNumber = 13;
    private static readonly pbc::MapField<int, int>.Codec _map_allRideNum_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 106);
    private readonly pbc::MapField<int, int> allRideNum_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> AllRideNum {
      get { return allRideNum_; }
    }

    /// <summary>Field number for the "allWeaponSkinNum" field.</summary>
    public const int AllWeaponSkinNumFieldNumber = 14;
    private static readonly pbc::MapField<int, int>.Codec _map_allWeaponSkinNum_codec
        = new pbc::MapField<int, int>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForInt32(16, 0), 114);
    private readonly pbc::MapField<int, int> allWeaponSkinNum_ = new pbc::MapField<int, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, int> AllWeaponSkinNum {
      get { return allWeaponSkinNum_; }
    }

    /// <summary>Field number for the "isFashionInit" field.</summary>
    public const int IsFashionInitFieldNumber = 15;
    private bool isFashionInit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsFashionInit {
      get { return isFashionInit_; }
      set {
        isFashionInit_ = value;
      }
    }

    /// <summary>Field number for the "isRideInit" field.</summary>
    public const int IsRideInitFieldNumber = 16;
    private bool isRideInit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRideInit {
      get { return isRideInit_; }
      set {
        isRideInit_ = value;
      }
    }

    /// <summary>Field number for the "isWeaponSkinInit" field.</summary>
    public const int IsWeaponSkinInitFieldNumber = 17;
    private bool isWeaponSkinInit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsWeaponSkinInit {
      get { return isWeaponSkinInit_; }
      set {
        isWeaponSkinInit_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FashionMgr);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FashionMgr other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!WearInfo.Equals(other.WearInfo)) return false;
      if (!FashionDatas.Equals(other.FashionDatas)) return false;
      if (!UnlockColor.Equals(other.UnlockColor)) return false;
      if (!FashionReward.Equals(other.FashionReward)) return false;
      if (!AllFashion.Equals(other.AllFashion)) return false;
      if (!AllRide.Equals(other.AllRide)) return false;
      if (!AllWeaponSkin.Equals(other.AllWeaponSkin)) return false;
      if (!FashionAdvance.Equals(other.FashionAdvance)) return false;
      if (FashionCollectPoint != other.FashionCollectPoint) return false;
      if (RideCollectPoint != other.RideCollectPoint) return false;
      if (WeaponSkinCollectPoint != other.WeaponSkinCollectPoint) return false;
      if (!AllFashionNum.Equals(other.AllFashionNum)) return false;
      if (!AllRideNum.Equals(other.AllRideNum)) return false;
      if (!AllWeaponSkinNum.Equals(other.AllWeaponSkinNum)) return false;
      if (IsFashionInit != other.IsFashionInit) return false;
      if (IsRideInit != other.IsRideInit) return false;
      if (IsWeaponSkinInit != other.IsWeaponSkinInit) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= WearInfo.GetHashCode();
      hash ^= FashionDatas.GetHashCode();
      hash ^= UnlockColor.GetHashCode();
      hash ^= FashionReward.GetHashCode();
      hash ^= AllFashion.GetHashCode();
      hash ^= AllRide.GetHashCode();
      hash ^= AllWeaponSkin.GetHashCode();
      hash ^= FashionAdvance.GetHashCode();
      if (FashionCollectPoint != 0) hash ^= FashionCollectPoint.GetHashCode();
      if (RideCollectPoint != 0) hash ^= RideCollectPoint.GetHashCode();
      if (WeaponSkinCollectPoint != 0) hash ^= WeaponSkinCollectPoint.GetHashCode();
      hash ^= AllFashionNum.GetHashCode();
      hash ^= AllRideNum.GetHashCode();
      hash ^= AllWeaponSkinNum.GetHashCode();
      if (IsFashionInit != false) hash ^= IsFashionInit.GetHashCode();
      if (IsRideInit != false) hash ^= IsRideInit.GetHashCode();
      if (IsWeaponSkinInit != false) hash ^= IsWeaponSkinInit.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      wearInfo_.WriteTo(output, _map_wearInfo_codec);
      fashionDatas_.WriteTo(output, _map_fashionDatas_codec);
      unlockColor_.WriteTo(output, _map_unlockColor_codec);
      fashionReward_.WriteTo(output, _map_fashionReward_codec);
      allFashion_.WriteTo(output, _map_allFashion_codec);
      allRide_.WriteTo(output, _map_allRide_codec);
      allWeaponSkin_.WriteTo(output, _map_allWeaponSkin_codec);
      fashionAdvance_.WriteTo(output, _map_fashionAdvance_codec);
      if (FashionCollectPoint != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(FashionCollectPoint);
      }
      if (RideCollectPoint != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(RideCollectPoint);
      }
      if (WeaponSkinCollectPoint != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(WeaponSkinCollectPoint);
      }
      allFashionNum_.WriteTo(output, _map_allFashionNum_codec);
      allRideNum_.WriteTo(output, _map_allRideNum_codec);
      allWeaponSkinNum_.WriteTo(output, _map_allWeaponSkinNum_codec);
      if (IsFashionInit != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsFashionInit);
      }
      if (IsRideInit != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(IsRideInit);
      }
      if (IsWeaponSkinInit != false) {
        output.WriteRawTag(136, 1);
        output.WriteBool(IsWeaponSkinInit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      wearInfo_.WriteTo(ref output, _map_wearInfo_codec);
      fashionDatas_.WriteTo(ref output, _map_fashionDatas_codec);
      unlockColor_.WriteTo(ref output, _map_unlockColor_codec);
      fashionReward_.WriteTo(ref output, _map_fashionReward_codec);
      allFashion_.WriteTo(ref output, _map_allFashion_codec);
      allRide_.WriteTo(ref output, _map_allRide_codec);
      allWeaponSkin_.WriteTo(ref output, _map_allWeaponSkin_codec);
      fashionAdvance_.WriteTo(ref output, _map_fashionAdvance_codec);
      if (FashionCollectPoint != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(FashionCollectPoint);
      }
      if (RideCollectPoint != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(RideCollectPoint);
      }
      if (WeaponSkinCollectPoint != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(WeaponSkinCollectPoint);
      }
      allFashionNum_.WriteTo(ref output, _map_allFashionNum_codec);
      allRideNum_.WriteTo(ref output, _map_allRideNum_codec);
      allWeaponSkinNum_.WriteTo(ref output, _map_allWeaponSkinNum_codec);
      if (IsFashionInit != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsFashionInit);
      }
      if (IsRideInit != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(IsRideInit);
      }
      if (IsWeaponSkinInit != false) {
        output.WriteRawTag(136, 1);
        output.WriteBool(IsWeaponSkinInit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += wearInfo_.CalculateSize(_map_wearInfo_codec);
      size += fashionDatas_.CalculateSize(_map_fashionDatas_codec);
      size += unlockColor_.CalculateSize(_map_unlockColor_codec);
      size += fashionReward_.CalculateSize(_map_fashionReward_codec);
      size += allFashion_.CalculateSize(_map_allFashion_codec);
      size += allRide_.CalculateSize(_map_allRide_codec);
      size += allWeaponSkin_.CalculateSize(_map_allWeaponSkin_codec);
      size += fashionAdvance_.CalculateSize(_map_fashionAdvance_codec);
      if (FashionCollectPoint != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FashionCollectPoint);
      }
      if (RideCollectPoint != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RideCollectPoint);
      }
      if (WeaponSkinCollectPoint != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WeaponSkinCollectPoint);
      }
      size += allFashionNum_.CalculateSize(_map_allFashionNum_codec);
      size += allRideNum_.CalculateSize(_map_allRideNum_codec);
      size += allWeaponSkinNum_.CalculateSize(_map_allWeaponSkinNum_codec);
      if (IsFashionInit != false) {
        size += 1 + 1;
      }
      if (IsRideInit != false) {
        size += 2 + 1;
      }
      if (IsWeaponSkinInit != false) {
        size += 2 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FashionMgr other) {
      if (other == null) {
        return;
      }
      wearInfo_.MergeFrom(other.wearInfo_);
      fashionDatas_.MergeFrom(other.fashionDatas_);
      unlockColor_.MergeFrom(other.unlockColor_);
      fashionReward_.MergeFrom(other.fashionReward_);
      allFashion_.MergeFrom(other.allFashion_);
      allRide_.MergeFrom(other.allRide_);
      allWeaponSkin_.MergeFrom(other.allWeaponSkin_);
      fashionAdvance_.MergeFrom(other.fashionAdvance_);
      if (other.FashionCollectPoint != 0) {
        FashionCollectPoint = other.FashionCollectPoint;
      }
      if (other.RideCollectPoint != 0) {
        RideCollectPoint = other.RideCollectPoint;
      }
      if (other.WeaponSkinCollectPoint != 0) {
        WeaponSkinCollectPoint = other.WeaponSkinCollectPoint;
      }
      allFashionNum_.MergeFrom(other.allFashionNum_);
      allRideNum_.MergeFrom(other.allRideNum_);
      allWeaponSkinNum_.MergeFrom(other.allWeaponSkinNum_);
      if (other.IsFashionInit != false) {
        IsFashionInit = other.IsFashionInit;
      }
      if (other.IsRideInit != false) {
        IsRideInit = other.IsRideInit;
      }
      if (other.IsWeaponSkinInit != false) {
        IsWeaponSkinInit = other.IsWeaponSkinInit;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            wearInfo_.AddEntriesFrom(input, _map_wearInfo_codec);
            break;
          }
          case 18: {
            fashionDatas_.AddEntriesFrom(input, _map_fashionDatas_codec);
            break;
          }
          case 26: {
            unlockColor_.AddEntriesFrom(input, _map_unlockColor_codec);
            break;
          }
          case 34: {
            fashionReward_.AddEntriesFrom(input, _map_fashionReward_codec);
            break;
          }
          case 42: {
            allFashion_.AddEntriesFrom(input, _map_allFashion_codec);
            break;
          }
          case 50: {
            allRide_.AddEntriesFrom(input, _map_allRide_codec);
            break;
          }
          case 58: {
            allWeaponSkin_.AddEntriesFrom(input, _map_allWeaponSkin_codec);
            break;
          }
          case 66: {
            fashionAdvance_.AddEntriesFrom(input, _map_fashionAdvance_codec);
            break;
          }
          case 72: {
            FashionCollectPoint = input.ReadInt32();
            break;
          }
          case 80: {
            RideCollectPoint = input.ReadInt32();
            break;
          }
          case 88: {
            WeaponSkinCollectPoint = input.ReadInt32();
            break;
          }
          case 98: {
            allFashionNum_.AddEntriesFrom(input, _map_allFashionNum_codec);
            break;
          }
          case 106: {
            allRideNum_.AddEntriesFrom(input, _map_allRideNum_codec);
            break;
          }
          case 114: {
            allWeaponSkinNum_.AddEntriesFrom(input, _map_allWeaponSkinNum_codec);
            break;
          }
          case 120: {
            IsFashionInit = input.ReadBool();
            break;
          }
          case 128: {
            IsRideInit = input.ReadBool();
            break;
          }
          case 136: {
            IsWeaponSkinInit = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            wearInfo_.AddEntriesFrom(ref input, _map_wearInfo_codec);
            break;
          }
          case 18: {
            fashionDatas_.AddEntriesFrom(ref input, _map_fashionDatas_codec);
            break;
          }
          case 26: {
            unlockColor_.AddEntriesFrom(ref input, _map_unlockColor_codec);
            break;
          }
          case 34: {
            fashionReward_.AddEntriesFrom(ref input, _map_fashionReward_codec);
            break;
          }
          case 42: {
            allFashion_.AddEntriesFrom(ref input, _map_allFashion_codec);
            break;
          }
          case 50: {
            allRide_.AddEntriesFrom(ref input, _map_allRide_codec);
            break;
          }
          case 58: {
            allWeaponSkin_.AddEntriesFrom(ref input, _map_allWeaponSkin_codec);
            break;
          }
          case 66: {
            fashionAdvance_.AddEntriesFrom(ref input, _map_fashionAdvance_codec);
            break;
          }
          case 72: {
            FashionCollectPoint = input.ReadInt32();
            break;
          }
          case 80: {
            RideCollectPoint = input.ReadInt32();
            break;
          }
          case 88: {
            WeaponSkinCollectPoint = input.ReadInt32();
            break;
          }
          case 98: {
            allFashionNum_.AddEntriesFrom(ref input, _map_allFashionNum_codec);
            break;
          }
          case 106: {
            allRideNum_.AddEntriesFrom(ref input, _map_allRideNum_codec);
            break;
          }
          case 114: {
            allWeaponSkinNum_.AddEntriesFrom(ref input, _map_allWeaponSkinNum_codec);
            break;
          }
          case 120: {
            IsFashionInit = input.ReadBool();
            break;
          }
          case 128: {
            IsRideInit = input.ReadBool();
            break;
          }
          case 136: {
            IsWeaponSkinInit = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
